### ISSUE TITLE
bsee | data API based on by API number

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/energydata#1]
- Get data based on API number
- The basic data used for bsee data analysis should be obtained.

**Comment by JayachandraJangiti** [comment]
1. webdriver is used to open and run chrome automatically.
2. By is used for accessing specific HTML elements by their names or id or any other unique identities.
3. get(url) is used to open specific url in our chrome webdriver.
4. driver.find_element(By.XPATH) is used to acceess specific element by their x_path.
5. send_keys(input_data) is used to send out input values.
6. button.click() is used to click automatically.
7. driver.implicitly_wait(250) In order to Wait for the page to load.


Process :

step-1 : Given url will be opened in chrome webdriver using driver.get() method.
step-2 : Given API ID will be given to text box that is accessed uniquely using by.XPATH method.
step-3 : submit query buttons are clicked using Element.click() method, then content will be shown.
step-4 : CSV_Button.click() is clicked
step-5 : Now, Temporary files are downloaded.
step-6 : Temporary files extensions are changed to CSV.
step-7 : CSV files of a specified directory are filtered using OS module.
step-8 : Path of newly created CSV file will be copied.
step-9 : That path is used to read CSV file as Dataframe.
